controller_list:
  - name: fake_dynamixel_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
initial:  # Define initial robot poses.
  - group: dynamixel_arm
    pose: home